spring:
  application:
    name: authentication-service

  datasource:
    url: jdbc:mysql://localhost:3306/authentication_service_db?createDatabaseIfNotExist=true
    username: root
    password: hung123
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      minimum-idle: 5       # Minimum number of idle connections in the pool
      maximum-pool-size: 20  # Maximum number of connections in the pool
      idle-timeout: 30000    # (30s) Time before an idle connection is removed
      max-lifetime: 1800000  # (30m) Maximum lifetime of a connection
      connection-timeout: 30000 # (30s) Timeout for getting a new connection
      pool-name: MyHikariPool # Custom pool name (useful for logging)

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
    enabled: true

  data:
    redis:
      host: localhost
      port: 6379
      password: redispassword

server:
  servlet:
    context-path: /authentication-service
  port: 8081

application:
  security:
    jwt:
      private-key: MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCsWfY1ni8MeinlmHxU5KmdAKMwGIokfYCP+tumb/uMDPXnY+BN8Fc9MjWHlwm7IghYkqPPk04m8xW5cmjHq1po+DWCCVnZxGDDbNkhT3YEFKvHhKOQFjwHNNUQB9lR+HCADhHjPOv+icu13Yesxoe/tCQ9k0Vd0rSgxN4dRLk9p0G6U3V3Fm6uZFx2aGDcTDR6jqNUjnZ2Yi5nWjL4Ip6EzWj8dnkZISmXr9hLEKQsIXYeWXI+Go5hF378Cy+IOVmsRT6gGadZtk34zezrnKGbv9k4JnGwAEXAzsAAUvLlJx9erZzZK9mIbqet9cv0ayhTZOUNhejmS35eYjiKx+V/AgMBAAECggEABsI4X33mhmy7+97w8TtOU3PU8mvj7u5k/kBuIKa/jIxtkDdgcm38Xc/8PWb04LvC7AZEGj3CkNBzh6Qu67WShA9HueO3/EwxJzi7gwzkqeBNpDNVXq8gh3/Q4yILqaU+dCcZGHopHwA0VttrGKFobWIZEbkWvUkoAC34L9mkEgDOnT1w2Zsbmh+qg16lTcM+k0t00AzHtEs7vJx3aW6/2abi9kiPZ8uKHF/tbBP/h/O48nrUL41f3qhb4asCHBG15j4qx8LFLwh1aniPmFT4Hg/drDyhsbFCSScPz8D+kSV416hTHm+XCXsZsaYFUMwAS3OJoAGVNzzkh0k96rD1cQKBgQDZK9jRTftJVieQSk5cx98m6qDMdqLYJ/brgIdLuKJbcWsLSTZzwuDth5CBkEgs22UP7DIOyausGv6Sua6X9qtC824eRcZDSLL5ITRxAaToy/9T75Mwu+h8tJXzQYkTd6JJmKYx/zEsqmUiJ7Aixg08RttHYwuYWper7RjaCVng/QKBgQDLKqnZDJ8cDswsfhDI3sfdS/3EMHBTF70jcKpCgG5nS0rL89h03aCq1r4jh3EL8JYPHagE/Fig7QW+b38UX5F6iWs+10hW7/pSW+KXhE7vsavT90MsZr/uQt+mz9djTHG1/BneIAjfXO2DdSrefbmnkjtp6ejC0ThT6zuzx3f3KwKBgQCsc98mxjAHmnysXfVARA92TdcGxiamU4YGmPfXL3Tt/HCuc6Lj5hrLRF2CJVrLFCV6sWtGxuqmLoF9bimwztZMwhXtwCaig3Zr0uxb2JxlqKjGtHZDutPxQ03X73C0nsmme6tuBGG+QEkzCCUcV/1mojW6yHIKt9W9VvfnHInc2QKBgEWhOJbv8XQPSkCRcDU3zS32BmH/6+8+eo8z5NZn5+606kyeJPhgoNkMQhwxJjheWz+Q/W3AAqwcr9RFqDsWSejCQiRGaj+JfbROU4l0Sg1ySh6aZsZH7M2+06H7J6mboHkrjr4HIqNS2QAt3uRkGIXq4zv4c9KZHAH+4/ZIjcADAoGAdEZdKITD7lgoOUtm4eDEhojGyElGu3C+bWVmhmdUmPb/u/MS5ssh3kDXWBmDb+Tj3+p+11qtrb9hC8zTgeobLWooqun+l/VXXsiWAYbVn1R9JfdMi4CFFpphoJD9LxDVsJa1e+5PWONYEaWQ3p+xTngur9fJlSo4JIjXlxE+flU=
      public-key: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEArFn2NZ4vDHop5Zh8VOSpnQCjMBiKJH2Aj/rbpm/7jAz152PgTfBXPTI1h5cJuyIIWJKjz5NOJvMVuXJox6taaPg1gglZ2cRgw2zZIU92BBSrx4SjkBY8BzTVEAfZUfhwgA4R4zzr/onLtd2HrMaHv7QkPZNFXdK0oMTeHUS5PadBulN1dxZurmRcdmhg3Ew0eo6jVI52dmIuZ1oy+CKehM1o/HZ5GSEpl6/YSxCkLCF2HllyPhqOYRd+/AsviDlZrEU+oBmnWbZN+M3s65yhm7/ZOCZxsABFwM7AAFLy5ScfXq2c2SvZiG6nrfXL9GsoU2TlDYXo5kt+XmI4isflfwIDAQAB
      expiration: 900000 # 15 minutes
      refresh-token:
        expiration: 3600000 # 1 hour

logging:
  level:
    org:
      springframework:
        security: DEBUG